import { chromium } from 'playwright'
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 600, height: 450 } })
const page = await ctx.newPage()
page.on('pageerror', e => console.log('PAGEERROR:', e.message))
await page.goto('http://localhost:5173/?t=' + Date.now(), { waitUntil: 'load' })
await page.waitForTimeout(500)
await page.evaluate(() => { const t = document.getElementById('tune'); if (t) t.style.display = 'none' })
await page.screenshot({ path: '/tmp/peanut-clean.png' })
await page.evaluate(() => window.__ragdoll.setTune({ DEBUG: true }))
await page.waitForTimeout(150)
await page.screenshot({ path: '/tmp/peanut-debug.png' })
await browser.close()
